version: 2.1

orbs:
  architect: giantswarm/architect@4.35.6

workflows:
  build-workflow:
    jobs:
      - architect/go-build:
          name: go-build
          context: architect
          binary: aws-collector
          resource_class: xlarge
          filters:
            tags:
              only: /^v.*/

      # Ensure that for every commit (all branches), and for every new release tag,
      # an image is pushed to Quay.
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-to-app-catalog-master
          context: architect
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "aws-collector"
          requires:
            - push-to-registries
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      # Ensure that for every commit (branch other than master)
      # there is an app version in the test catalog.
      # Note: Making this app usable in china needs manual approval
      # of the 'hold-push-to-aliyun-pr' job.
      - architect/push-to-app-catalog:
          name: push-to-app-catalog-pr
          context: architect
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "aws-collector"
          requires:
            - push-to-registries
          filters:
            branches:
              ignore: master

      - architect/push-to-app-collection:
          name: push-aws-collector-to-aws-app-collection
          context: architect
          app_name: "aws-collector"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-to-app-catalog-master
          filters:
            # Only do this when a new tag is created.
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
