image:
  name: "giantswarm/aws-collector"
  tag: "[[ .Version ]]"
Installation:
  V1:
    Registry:
      Domain: docker.io
pod:
  user:
    id: 1000
  group:
    id: 1000
ports:
  ingress:
    - name: "http"
      port: 8000
      protocol: "TCP"
project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
