image:
  name: "giantswarm/aws-collector"
  tag: "[[ .Version ]]"
pod:
  user:
    id: 1000
  group:
    id: 1000
ports:
  ingress:
    - name: "http"
      port: 8000
      protocol: "TCP"
project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

managementCluster:
  name: ""

aws:
  region: ""

trustedAdvisor:
  enabled: false

registry:
  domain: docker.io
