image:
  name: "giantswarm/aws-collector"
  tag: "[[ .Version ]]"
pod:
  user:
    id: 1000
  group:
    id: 1000
ports:
  ingress:
    - name: "http"
      port: 8000
      protocol: "TCP"
project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

managementCluster:
  name: ""

aws:
  region: ""
  accessKeyID: ""
  secretAccessKey: ""

trustedAdvisor:
  enabled: false

registry:
  domain: docker.io
  pullSecret:
    dockerConfigJSON: ""

verticalPodAutoscaler:
  enabled: true

# Add seccomp to pod security context
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
  runAsNonRoot: true

# Add seccomp to container security context
securityContext:
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL

serviceMonitor:
  enabled: true
  # -- (duration) Prometheus scrape interval.
  interval: "120s"
  # -- (duration) Prometheus scrape timeout.
  scrapeTimeout: "30s"
