apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  config.yaml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      aws:
        trustedAdvisor:
          enabled: '{{ .Values.trustedAdvisor.enabled }}'
        region: '{{ .Values.aws.region }}'
      registry:
      {{- if hasPrefix "cn-" .Values.aws.region }}
        domain: '{{ .Values.registry.domain }}'
        mirrors: '{{ range $i, $e := .Values.registry.mirrors }}{{ if $i }},{{end}}{{ $e }}{{end}}'
      {{ else }}
        domain: 'docker.io'
        mirrors: 'giantswarm.azurecr.io'
      {{- end }}
      installation:
        name: '{{ .Values.managementCluster.name }}'
      kubernetes:
        incluster: true
