{{- if .Capabilities.APIVersions.Has "kyverno.io/v2/PolicyException" }}
apiVersion: kyverno.io/v2
{{- else if .Capabilities.APIVersions.Has "kyverno.io/v2beta1/PolicyException" }}
apiVersion: kyverno.io/v2beta1
{{- else }}
apiVersion: kyverno.io/v2alpha1
{{- end }}
kind: PolicyException
metadata:
  name: {{ include "resource.default.name" . }}-exceptions
  namespace: {{ include "resource.default.namespace" . }}
spec:
  exceptions:
  - policyName: disallow-host-path
    ruleNames:
    - host-path
    - autogen-host-path
  - policyName: restrict-volume-types
    ruleNames:
    - restricted-volumes
    - autogen-restricted-volumes
  match:
    any:
    - resources:
        kinds:
        - Deployment
        - Pod
        - ReplicaSet
        namespaces:
        - {{ include "resource.default.namespace" . }}
        names:
        - {{ include "resource.default.name" . }}*
