apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    application.giantswarm.io/team: phoenix
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
spec:
  endpoints:
    - honorLabels: true
      interval: 120s
      scrapeTimeout: 30s
      path: /metrics
      port: metrics
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: node
          replacement: ${1}
  namespaceSelector:
    matchNames:
      - {{ include "resource.default.namespace" . }}
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
